# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |    
        pushd client
        npm ci
        npm run build --if-present  
        popd

        pushd server
        npm ci
        npm run build --if-present
        rm -rf node_modules    
        popd
    - name: Archive client
      uses: actions/upload-artifact@v1
      with:
        name: client
        path: client/build
    - name: Archive server
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: |
          server/*.js
          server/*.json
  deploy:
    name: deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy server
      uses: miked49er/rsync-deployments@v1.0
      with:
        switches: -avzr --delete
        path: server/
        remote_path: /var/tmp/server/
        remote_host: ${{ secrets.SSH_AIP_HOST }}
        remote_user: ${{ secrets.SSH_AIP_USER }}
        remote_key: ${{ secrets.SSH_AIP_KEY }}
    - name: deploy client
      uses: miked49er/rsync-deployments@v1.0
      with:
        switches: -avzr --delete
        path: client/build
        remote_path: /var/tmp/client/
        remote_host: ${{ secrets.SSH_AIP_HOST }}
        remote_user: ${{ secrets.SSH_AIP_USER }}
        remote_key: ${{ secrets.SSH_AIP_KEY }}
    
