name: Rentz-v1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |    
        pushd client
        npm ci
        npm run build --if-present  
        popd

        pushd server
        npm ci
        npm run build --if-present
        rm -rf node_modules    
        popd
    - name: Archive client
      uses: actions/upload-artifact@v1
      with:
        name: client
        path: client/build
    - name: Archive server
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: |
          server/*.js
          server/*.json
  copyToServer:
    name: deploy artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download server
      uses: actions/download-artifact@v1
      with:
        name: server
    - shell: bash
      run: |
        pwd
        ls -la
        ls -la server/
    - name: Download client
      uses: actions/download-artifact@v1
      with:
        name: client
    - shell: bash
      run: |
        pwd
        ls -la
        ls -la client/
    - name: deploy server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SSH_AIP_HOST }}
        username: ${{ secrets.SSH_AIP_USER }}
        privateKey : ${{ secrets.SSH_AIP_KEY }}
        passphrase :  ${{ secrets.SSH_AIP_PHRASE }}
        local: "server"
        remote: /var/tmp/github/server/
    - name: deploy client
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SSH_AIP_HOST }}
        username: ${{ secrets.SSH_AIP_USER }}
        privateKey : ${{ secrets.SSH_AIP_KEY }}
        passphrase :  ${{ secrets.SSH_AIP_PHRASE }}
        local: "client"
        remote: /var/tmp/github/client/
  deploy:
    needs: copyToServer
    runs-on: ubuntu-latest
    steps:
     - name: deploy client and server
       uses: garygrossgarten/github-action-ssh@release
       with:
         host: ${{ secrets.SSH_AIP_HOST }}
         username: ${{ secrets.SSH_AIP_USER }}
         privateKey: ${{ secrets.SSH_AIP_KEY }}
         passphrase :  ${{ secrets.SSH_AIP_PHRASE }}
         command: |
           rsync -avz --delete /var/tmp/github/client/ ${{ secrets.AIP_SSH_CLIENT_PATH }}
           kill $(netstat -lntp | grep 37303 | awk '{print $NF}' | cut -d/ -f1 )
           rsync -avz --delete /var/tmp/github/server/ ${{ secrets.AIP_SSH_SERVER_PATH }}
           cd ${{ secrets.AIP_SSH_SERVER_PATH }}
           nohup nodejs server.js &
